'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Container } from '@/components/container'
import { Footer } from '@/components/footer'
import { Navbar } from '@/components/navbar'
import { HeroAnimation } from '@/components/hero-animation'

export default function RobotsTxtGeneratorPage() {
  const [allowAll, setAllowAll] = useState(true)
  const [sitemap, setSitemap] = useState('https://example.com/sitemap.xml')
  const [disallowPaths, setDisallowPaths] = useState('/admin/\n/api/\n/_next/')
  const [crawlDelay, setCrawlDelay] = useState(0)
  const [allowGptBot, setAllowGptBot] = useState(true)
  const [allowClaudeBot, setAllowClaudeBot] = useState(true)
  const [allowGoogleExtended, setAllowGoogleExtended] = useState(true)
  const [allowPerplexityBot, setAllowPerplexityBot] = useState(true)
  const [allowCcBot, setAllowCcBot] = useState(true)

  const generate = () => {
    const lines: string[] = []
    lines.push('# Generated by TheProjectSEO robots.txt tool')
    lines.push('# https://theprojectseo.com/tools/robots-txt-generator')
    lines.push('')
    lines.push('User-agent: *')
    if (allowAll) {
      lines.push('Allow: /')
    }
    const disallows = disallowPaths.split('\n').map((s) => s.trim()).filter(Boolean)
    disallows.forEach((path) => lines.push(`Disallow: ${path}`))
    if (crawlDelay > 0) lines.push(`Crawl-delay: ${crawlDelay}`)
    lines.push('')

    const aiBots: Array<[string, boolean]> = [
      ['GPTBot', allowGptBot],
      ['ChatGPT-User', allowGptBot],
      ['ClaudeBot', allowClaudeBot],
      ['anthropic-ai', allowClaudeBot],
      ['Google-Extended', allowGoogleExtended],
      ['PerplexityBot', allowPerplexityBot],
      ['CCBot', allowCcBot],
    ]
    aiBots.forEach(([ua, allow]) => {
      lines.push(`User-agent: ${ua}`)
      lines.push(allow ? 'Allow: /' : 'Disallow: /')
      lines.push('')
    })

    if (sitemap) {
      lines.push(`Sitemap: ${sitemap}`)
    }
    return lines.join('\n')
  }

  const output = generate()
  const copy = () => navigator.clipboard.writeText(output)

  const inputClass = 'w-full rounded-md border border-border-emphasis bg-paper px-3 py-2 text-sm text-ink focus:outline-2 focus:-outline-offset-1 focus:outline-accent'
  const labelClass = 'block font-mono text-xs uppercase tracking-[0.1em] text-ash mb-1.5'

  return (
    <main className="overflow-hidden">
      <div className="relative overflow-hidden">
        <HeroAnimation />
        <Container className="relative">
          <Navbar />
          <div className="pt-16 pb-12 sm:pt-24 sm:pb-16">
            <div className="flex items-center gap-2 mb-4">
              <Link href="/tools" className="font-mono text-xs text-ash uppercase tracking-wider hover:text-accent">Tools</Link>
              <span className="text-ash">/</span>
              <span className="font-mono text-xs text-accent uppercase tracking-wider">Robots.txt Generator</span>
            </div>
            <p className="font-mono text-sm font-semibold uppercase tracking-[0.15em] text-accent mb-4">Free Generator</p>
            <h1 className="font-display text-[clamp(36px,5vw,72px)] font-medium leading-[0.95] tracking-[-0.02em] text-ink">Robots.txt Generator</h1>
            <p className="mt-4 max-w-2xl text-lg leading-relaxed text-stone">Build a robots.txt file with explicit AI-bot controls for GPTBot, ClaudeBot, Google-Extended, PerplexityBot, and CCBot. Most generators forget these.</p>
            <p className="mt-2 font-mono text-xs text-ash">Free forever. No signup. Runs in your browser.</p>
          </div>
        </Container>
      </div>

      <div className="bg-paper py-16">
        <Container>
          <div className="grid grid-cols-1 gap-12 lg:grid-cols-2">
            <div>
              <h2 className="font-heading text-xl font-semibold text-ink mb-8">Configuration</h2>
              <div className="space-y-6">
                <label className="flex items-center gap-3 text-sm text-ink">
                  <input type="checkbox" checked={allowAll} onChange={(e) => setAllowAll(e.target.checked)} className="size-4 rounded border-border-emphasis text-accent" />
                  Allow search bots to crawl everything by default
                </label>
                <div>
                  <label className={labelClass}>Disallow paths (one per line)</label>
                  <textarea value={disallowPaths} onChange={(e) => setDisallowPaths(e.target.value)} rows={5} className={inputClass} />
                </div>
                <div>
                  <label className={labelClass}>Sitemap URL</label>
                  <input type="url" value={sitemap} onChange={(e) => setSitemap(e.target.value)} className={inputClass} />
                </div>
                <div>
                  <label className={labelClass}>Crawl delay (seconds, 0 = none)</label>
                  <input type="number" min={0} value={crawlDelay} onChange={(e) => setCrawlDelay(Number(e.target.value))} className={inputClass} />
                </div>
                <div className="pt-4 border-t border-border">
                  <div className="font-heading text-sm font-semibold text-ink mb-3">AI / LLM training bots</div>
                  <p className="text-xs text-ash mb-4">Allow = your content can appear in AI answers. Disallow = you opt out of training and citation.</p>
                  <div className="space-y-2">
                    <label className="flex items-center gap-3 text-sm text-ink">
                      <input type="checkbox" checked={allowGptBot} onChange={(e) => setAllowGptBot(e.target.checked)} className="size-4 rounded border-border-emphasis text-accent" />
                      Allow GPTBot / ChatGPT-User (OpenAI)
                    </label>
                    <label className="flex items-center gap-3 text-sm text-ink">
                      <input type="checkbox" checked={allowClaudeBot} onChange={(e) => setAllowClaudeBot(e.target.checked)} className="size-4 rounded border-border-emphasis text-accent" />
                      Allow ClaudeBot / anthropic-ai (Anthropic)
                    </label>
                    <label className="flex items-center gap-3 text-sm text-ink">
                      <input type="checkbox" checked={allowGoogleExtended} onChange={(e) => setAllowGoogleExtended(e.target.checked)} className="size-4 rounded border-border-emphasis text-accent" />
                      Allow Google-Extended (Gemini, Bard, AI Overviews training)
                    </label>
                    <label className="flex items-center gap-3 text-sm text-ink">
                      <input type="checkbox" checked={allowPerplexityBot} onChange={(e) => setAllowPerplexityBot(e.target.checked)} className="size-4 rounded border-border-emphasis text-accent" />
                      Allow PerplexityBot
                    </label>
                    <label className="flex items-center gap-3 text-sm text-ink">
                      <input type="checkbox" checked={allowCcBot} onChange={(e) => setAllowCcBot(e.target.checked)} className="size-4 rounded border-border-emphasis text-accent" />
                      Allow CCBot (Common Crawl)
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <div className="flex items-center justify-between mb-4">
                <h2 className="font-heading text-xl font-semibold text-ink">Output</h2>
                <button onClick={copy} className="font-mono text-xs uppercase tracking-[0.1em] text-accent hover:text-ink transition-colors">
                  Copy to clipboard
                </button>
              </div>
              <pre className="bg-ink text-paper p-6 font-mono text-xs leading-relaxed overflow-x-auto max-h-[600px] overflow-y-auto">{output}</pre>
              <p className="mt-4 text-xs text-ash">Save this as <code className="font-mono text-accent">robots.txt</code> at your site root (e.g. https://example.com/robots.txt).</p>
            </div>
          </div>
        </Container>
      </div>
      <Footer />
    </main>
  )
}
