"""
SEO-specific taxonomies for TheProjectSEO embedding analysis.

Defines topic taxonomy, common questions, and entity taxonomy
specific to SEO services and digital marketing.
"""

# Topic Taxonomy for SEO Services
DEFAULT_SEO_TOPICS = {
    "seo_fundamentals": [
        "keyword research",
        "on-page SEO",
        "technical SEO",
        "off-page SEO",
        "local SEO",
        "content optimization",
        "meta tags optimization",
        "internal linking",
        "backlink building",
        "site architecture",
    ],
    "technical_seo": [
        "site speed optimization",
        "Core Web Vitals",
        "mobile optimization",
        "crawlability",
        "indexability",
        "structured data",
        "schema markup",
        "XML sitemaps",
        "robots.txt",
        "canonical tags",
        "hreflang implementation",
        "HTTPS migration",
    ],
    "content_strategy": [
        "content creation",
        "content marketing",
        "blog strategy",
        "pillar pages",
        "topic clusters",
        "E-E-A-T",
        "content freshness",
        "user intent matching",
        "semantic SEO",
        "content gap analysis",
    ],
    "link_building": [
        "backlink acquisition",
        "link outreach",
        "digital PR",
        "guest posting",
        "broken link building",
        "skyscraper technique",
        "link equity",
        "toxic link removal",
        "disavow file",
    ],
    "local_seo": [
        "Google Business Profile",
        "local citations",
        "NAP consistency",
        "local schema markup",
        "local link building",
        "review management",
        "local keyword targeting",
        "geo-targeting",
    ],
    "analytics_reporting": [
        "Google Analytics",
        "Google Search Console",
        "rank tracking",
        "traffic analysis",
        "conversion tracking",
        "KPI reporting",
        "ROI measurement",
        "competitor analysis",
    ],
    "emerging_seo": [
        "AI search optimization",
        "voice search SEO",
        "featured snippets",
        "People Also Ask",
        "zero-click searches",
        "ChatGPT optimization",
        "Perplexity optimization",
        "generative engine optimization",
        "answer engine optimization",
        "AEO",
    ],
}

# Common SEO Questions
DEFAULT_SEO_QUESTIONS = [
    "What is SEO and how does it work?",
    "How long does it take to see SEO results?",
    "How much does SEO cost?",
    "What is the difference between on-page and off-page SEO?",
    "What are backlinks and why are they important?",
    "How do I do keyword research?",
    "What are Core Web Vitals?",
    "How do I optimize for local SEO?",
    "What is technical SEO?",
    "How do I improve my Google rankings?",
    "What is E-E-A-T in SEO?",
    "How do I optimize for featured snippets?",
    "What is schema markup?",
    "How do I audit my website for SEO?",
    "What is the difference between white hat and black hat SEO?",
    "How do I optimize for mobile SEO?",
    "What are the most important ranking factors?",
    "How do I track SEO performance?",
    "What is content optimization?",
    "How do I recover from a Google penalty?",
    "What is link building?",
    "How do I optimize for voice search?",
    "What is international SEO?",
    "How do I optimize for AI search engines?",
    "What is answer engine optimization (AEO)?",
]

# Entity Taxonomy for SEO
DEFAULT_SEO_ENTITY_TAXONOMY = {
    "tools_platforms": [
        "Google Search Console",
        "Google Analytics",
        "Ahrefs",
        "SEMrush",
        "Moz",
        "Screaming Frog",
        "Google PageSpeed Insights",
        "GTmetrix",
        "Yoast SEO",
        "Rank Math",
        "Sitebulb",
        "DeepCrawl",
        "Majestic",
        "BrightEdge",
        "Conductor",
    ],
    "search_engines": [
        "Google",
        "Bing",
        "Yahoo",
        "DuckDuckGo",
        "Baidu",
        "Yandex",
        "ChatGPT",
        "Perplexity",
        "Claude",
        "Gemini",
    ],
    "concepts_frameworks": [
        "E-E-A-T",
        "Core Web Vitals",
        "PageRank",
        "TrustRank",
        "domain authority",
        "page authority",
        "crawl budget",
        "link equity",
        "topical authority",
        "semantic relevance",
        "user experience signals",
        "dwell time",
        "pogo-sticking",
        "click-through rate",
        "SERP features",
        "knowledge graph",
        "featured snippets",
        "People Also Ask",
        "local pack",
        "generative engine optimization",
        "answer engine optimization",
    ],
    "algorithms_updates": [
        "Panda",
        "Penguin",
        "Hummingbird",
        "RankBrain",
        "BERT",
        "MUM",
        "Helpful Content Update",
        "Core Algorithm Update",
        "Product Reviews Update",
        "Page Experience Update",
        "Mobile-First Indexing",
    ],
    "standards_protocols": [
        "HTML5",
        "schema.org",
        "JSON-LD",
        "Open Graph",
        "Twitter Cards",
        "robots.txt",
        "XML sitemap",
        "canonical tags",
        "hreflang",
        "noindex",
        "nofollow",
        "HTTP/2",
        "HTTPS",
        "SSL/TLS",
    ],
    "organizations_resources": [
        "Google",
        "Bing Webmaster Tools",
        "W3C",
        "schema.org",
        "Search Engine Land",
        "Moz Blog",
        "Search Engine Journal",
        "Google Search Central",
        "Bing Webmaster Blog",
    ],
}
